version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "No pre-build steps"
  build:
    commands:
      - echo "No build step"
  post_build:
    commands:
      - echo "Build complete!"
artifacts:
  files:
    - '**/*'
