version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Preparing deployment package...
      - mkdir -p deploy
      - cp -r * deploy/  # Copy all files into the deploy folder
      - cd deploy
      - zip -r ../deployment.zip *  # Create a zip file for deployment

artifacts:
  files:
    - deployment.zip  # Specify the zip file that will be used in CodeDeploy
